CREATE TABLE users (
  id        INT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username  VARCHAR(50)               NOT NULL UNIQUE,
  password  VARCHAR(50)               NOT NULL
);

CREATE TABLE IF NOT EXISTS files (
  id           INT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR(255) NOT NULL UNIQUE,
  mime_type    VARCHAR(255) NOT NULL,
  data         BYTEA        NOT NULL,
  uploaded_at  TIMESTAMP    NOT NULL,
  size         BIGINT       NOT NULL
);